name: Auto Commit

on:
  schedule:
    - cron: "0 5,6,7,8,9,10,11,12,13,14 * * *"


  workflow_dispatch:  # هذا يسمح بتشغيله يدويًا إذا لزم الأمر

jobs:
  commit:
    runs-on: ubuntu-latest  # تشغيل على سيرفر Linux

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # تحميل مستودعك إلى بيئة التشغيل

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"

      - name: Modify File
        run: |
          echo "Updated on $(date)" >> test_file.txt  # إضافة تحديث إلى الملف

      - name: Commit and Push
        run: |
          git add .
          git commit -m "Automated commit - $(date)" || exit 0  # تنفيذ commit
          git push  # رفع التغييرات إلى المستودع
