name: Auto Commit

on:
  schedule:
    - cron: "0 5,6,7,8,9,10,11,12,13,14 * * *"

  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # نحتاج لتعطيل هذا حتى نستخدم التوكن الخاص بنا

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"

      - name: Modify File
        run: echo "Updated on $(date)" >> test_file.txt

      - name: Commit and Push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git add .
          git commit -m "Automated commit - $(date)" || exit 0
          git push https://$GH_PAT@github.com/LechehebDjaafar/workflows.git HEAD:main
